### ISSUE TITLE
SMTP Integration for More Flexible Email Sending

### ISSUE THREAD

**Issue by sheyzi** [KoesterJannik/sveltekit-repo-starter#2]
Hi @KoesterJannik,

Thanks for creating this awesome SvelteKit starter template! It looks very useful.

I noticed you're currently using SES for email functionality. While SES is a great option, it might be worth considering SMTP integration as well. This would allow users to leverage their preferred email provider for sending emails, potentially offering more flexibility and control.

Of course, setting up a separate email server might be an additional step for some users. However, I believe the benefits of wider compatibility and potentially lower costs could make it a valuable addition.

What do you think about exploring the possibility of adding optional SMTP integration? I'd be happy to discuss this further.

**I wouldn't mind implementing it**

**Comment by KoesterJannik** [comment]
Hi, sounds good to me. Then the user can decide what they want to use. Feel free to implement it, i will give it a review!
