### ISSUE TITLE
Add loading animation when navigating pages

### ISSUE THREAD

**Issue by sheyzi** [KoesterJannik/sveltekit-repo-starter#7]
Right now, when you click a button or link, there's no indication that the next page is loading. It just suddenly changes without any visual feedback. I suggest we add a loading animation to let users know that the page is loading in the background. This way, it will provide a better user experience and keep them informed during the page transition.

**Comment by KoesterJannik** [comment]
good idea, you wanna make this changes and create a pr?

**Comment by KoesterJannik** [comment]
maybe something generic, so we can reuse that over the whole application

**Comment by sheyzi** [comment]
Yeah, a simple component will work

**Comment by sheyzi** [comment]
I will make a PR
